package com.swein.sharcodecode.arpart.constants;

public class ARESSArrows {

    public final static String DETECTED_TARGET_MINIMUM_AREA_SIZE_FINISHED = "DETECTED_TARGET_MINIMUM_AREA_SIZE_FINISHED";
    public final static String DETECTING_TARGET_MINIMUM_AREA_SIZE = "DETECTING_TARGET_MINIMUM_AREA_SIZE";

    public final static String CAMERA_AND_PLANE_DISTANCE_TOO_CLOSE = "CAMERA_AND_PLANE_DISTANCE_TOO_CLOSE";
    public final static String CAMERA_AND_PLANE_DISTANCE_TOO_FAR = "CAMERA_AND_PLANE_DISTANCE_TOO_FAR";
    public final static String CAMERA_AND_PLANE_DISTANCE_OK = "CAMERA_AND_PLANE_DISTANCE_OK";
}
